import type { LayoutLoad } from './$types';

export const load = (() => {
	return {
		challenges: [
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/mwjogovjjnkz6f6yzdkp.jpg',
				title: 'Age Calculator App',
				url: '/age-calculator-app',
				description:
					'This challenge is designed to sharpen your JavaScript and form validation skills. Working with dates in JavaScript can be tricky, so this will be a nice test!',
				href: 'https://www.frontendmentor.io/challenges/age-calculator-app-dF9DFFpj-Q',
				type: 'app',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/fp0qtspesm6i0miyqncg.jpg',
				title: 'Interactive Pricing Component',
				url: '/interactive-pricing-component',
				description:
					"In this project, you'll build out an interactive pricing component complete with custom range input slider and pricing toggle. A perfect way to test your JS skills!",
				href: 'https://www.frontendmentor.io/challenges/interactive-pricing-component-t0m8PIyY8',
				type: 'components',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/tbvaexdry87sqjmbzt5o.jpg',
				title: 'Crowdfunding Product Page',
				url: '/crowdfunding-product-page',
				description:
					'This challenge will test both your layout and state management skills. As visitors make pledges, your goal is to keep track of the changes.',
				href: 'https://www.frontendmentor.io/challenges/crowdfunding-product-page-7uvcZe7ZR',
				type: 'pages',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/wdor1bppurckam2nrhwn.jpg',
				title: 'Blogr Landing Page',
				url: '/blogr-landing-page',
				description:
					"Flex your layout muscles with this landing page challenge. You'll mostly be working with HTML & CSS for this project with a tiny bit of JS for the mobile menu.",
				href: 'https://www.frontendmentor.io/challenges/blogr-landing-page-EX2RLAApP',
				type: 'pages',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/juir90bwmmvlo86g9paz.jpg',
				title: '3 Column Preview Card Component',
				url: '/3-column-preview-card',
				description:
					"This challenge is perfect if you're just getting started. The shift between the layouts will be a nice test if you're new to building responsive projects.",
				href: 'https://www.frontendmentor.io/challenges/3column-preview-card-component-pH92eAR2-',
				type: 'components',
				start_at: '2023-04-06T00:00:03.768Z',
				done_at: '2023-04-06T00:43:03.768Z',
				status: true,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/zjx3vvssz4f9zxr2djai.jpg',
				title: 'Calculator App',
				url: '/calculator-app',
				description:
					"This calculator app will be a great test of your CSS and JS skills especially. If you're wanting to practice using Grid, this challenge will be perfect for you!",
				href: 'https://www.frontendmentor.io/challenges/calculator-app-9lteq5N29',
				type: 'app',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/pigotdvhcch2b3wp9uuc.jpg',
				title: 'Sunnyside Agency Landing Page',
				url: '/sunnyside-agency-landing-page',
				description:
					"This challenge will be a perfect test of your layout and responsive skills. There's a tiny bit of JS for the mobile menu, but the focus is HTML & CSS.",
				href: 'https://www.frontendmentor.io/challenges/sunnyside-agency-landing-page-7yVs3B6ef',
				type: 'pages',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/hxkpctp6cd1meeytfdl2.jpg',
				title: 'Tip Calculator App',
				url: '/tip-calculator-app',
				description:
					'This small app is perfect for anyone starting to get to grips with JavaScript. The calculator functionality will be a nice test!',
				href: 'https://www.frontendmentor.io/challenges/tip-calculator-app-ugJNGbJUX',
				type: 'app',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/ouobx6tvyduidzio7wr7.jpg',
				title: 'Order Summary Component',
				url: '/order-summary-component',
				description: 'A perfect project for newbies who are starting to build confidence with layouts!',
				href: 'https://www.frontendmentor.io/challenges/order-summary-component-QlPmajDUj',
				type: 'components',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/j1ocp59n25odoftocgpi.jpg',
				title: 'Time Tracking Dashboard',
				url: '/time-tracking-dashboard',
				description:
					'A perfect opportunity to practice your CSS Grid skills. For anyone wanting to take it up a notch, we provide a JSON data file to practice working with data.',
				href: 'https://www.frontendmentor.io/challenges/time-tracking-dashboard-UIQ7167Jw',
				type: 'pages',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/fhzpdnabrek50hvhftnl.jpg',
				title: 'E-Commerce Product Page',
				url: '/e-commerce-product-page',
				description:
					"In this challenge, you'll build a beautiful product page. We'll be putting your JS skills to the test with a lightbox product gallery and cart functionality!",
				href: 'https://www.frontendmentor.io/challenges/ecommerce-product-page-UPsZ9MJp6',
				type: 'pages',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/rinokvkluq95madbvtmk.jpg',
				title: 'Nft Preview Card Component',
				url: '/nft-preview-card',
				description:
					'This HTML & CSS only challenge is perfect for anyone just starting out or anyone wanting a small project to play around with.',
				href: 'https://www.frontendmentor.io/challenges/nft-preview-card-component-SbdUL_w0U',
				type: 'components',
				start_at: '2023-03-16T14:17:00.000Z',
				done_at: '2023-03-16T14:48:00.000Z',
				status: true,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/i8zblmqsbqixz1tbhc0v.jpg',
				title: 'Interactive Comments Section',
				url: '/interactive-comments-section',
				description:
					"This is project will put your JavaScript skills to the test. We provide a JSON file to pull the data, but it's also a perfect project to build as a full-stack CRUD app!",
				href: 'https://www.frontendmentor.io/challenges/interactive-comments-section-iG1RugEG9',
				type: 'pages',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/sfl8uqvq75wnnr559ksp.jpg',
				title: 'Advice Generator App',
				url: '/advice-generator-app',
				description:
					"The perfect project if you're learning how to interact with 3rd-party APIs. This challenge uses the Advice Slip API to generate random quotes of advice.",
				href: 'https://www.frontendmentor.io/challenges/advice-generator-app-QdUG-13db',
				type: 'app',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/hxx2bhmtmeelt0a98zos.jpg',
				title: 'Interactive Rating Component',
				url: '/interactive-rating-component',
				description:
					'This is a nice, small project to practice handling user interactions and updating the DOM. Perfect for anyone who has learned the basics of JavaScript!',
				href: 'https://www.frontendmentor.io/challenges/interactive-rating-component-koxpeBUmI',
				type: 'components',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/rlaxdjplmeul4qe1qvh6.jpg',
				title: 'Intro Section With Dropdown Navigation',
				url: '/intro-section-with-dropdown-navigation',
				description:
					'This challenge will test your ability to create dropdown navigation menus, a common pattern on larger sites. It will also provide some nice basic layout challenges.',
				href: 'https://www.frontendmentor.io/challenges/intro-section-with-dropdown-navigation-ryaPetHE5',
				type: 'pages',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/xhxtaym7uzypzb37rpcc.jpg',
				title: 'Expenses Chart Component',
				url: '/expenses-chart-component',
				description:
					"In this challenge, you'll create a bar chart component from scratch. We provide a local JSON file, so you can add the chart data dynamically if you choose.",
				href: 'https://www.frontendmentor.io/challenges/expenses-chart-component-e7yJBUdjwt',
				type: 'components',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/lftjtn81b7brs2icc898.jpg',
				title: 'Product Preview Card Component',
				url: '/product-preview',
				description:
					'This HTML & CSS-only challenge will be perfect for anyone starting to build responsive projects.',
				href: 'https://www.frontendmentor.io/challenges/product-preview-card-component-GO7UmttRfa',
				type: 'components',
				start_at: '2023-04-07T03:15:55.306Z',
				done_at: '2023-04-07T03:51:55.306Z',
				status: true,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/u57dcsnhvoalnixjt6kb.jpg',
				title: 'Interactive Card Details Form',
				url: '/interactive-card-details-form',
				description:
					'This fun project will be an excellent way to practice DOM manipulation and form validation while also putting your HTML and CSS skills to the test.',
				href: 'https://www.frontendmentor.io/challenges/interactive-card-details-form-XpS8cKZDWw',
				type: 'pages',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/wgwtjhvnsjnax4k6rdqw.jpg',
				title: 'Notifications Page',
				url: '/notifications-page',
				description:
					"This project will be a brilliant test of your HTML, CSS, and basic JavaScript skills. You'll use JS to toggle the visual state of the notifications.",
				href: 'https://www.frontendmentor.io/challenges/notifications-page-DqK5QAmKbC',
				type: 'pages',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/lpwvfibpdyycvjpukkec.jpg',
				title: 'Multi-Step Form',
				url: '/multi-step-form',
				description:
					'An excellent test for your form-building and JS skills, this project will pose many challenges along the way to completion.',
				href: 'https://www.frontendmentor.io/challenges/multistep-form-YVAnSdqQBJ',
				type: 'pages',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/b03akozsxsouireonkkd.jpg',
				title: 'Results Summary Component',
				url: '/results-summary-component',
				description:
					'This challenge has something for everyone. It’s a HTML and CSS only project, but we’ve also provided a JSON file of the test results for anyone wanting to practice JS.',
				href: 'https://www.frontendmentor.io/challenges/results-summary-component-CE_K6s0maV',
				type: 'components',
				start_at: '',
				done_at: '',
				status: false,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/sucvvhutd4codsxpzvw7.jpg',
				title: 'Stats Preview Card Component',
				slug: 'stats-preview-card-component',
				url: '/stats-preview-card',
				description:
					"This is a great small challenge to help get you used to building to a design. There's no JS in this project, so you'll be able to focus on your HTML & CSS skills.",
				href: 'https://www.frontendmentor.io/challenges/stats-preview-card-component-8JqbgoU62',
				type: 'components',
				start_at: '2023-03-20T07:52:00.000Z',
				done_at: '2023-03-20T08:28:00.000Z',
				status: true,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/abbzt6kmkawmpbj7evxx.jpg',
				title: 'News Homepage',
				slug: 'news-homepage',
				url: '/news-homepage',
				description:
					'This news homepage will be an excellent opportunity to practice your CSS Grid skills. There will be lots of tricky decisions to make and plenty of learning opportunities!',
				href: 'https://www.frontendmentor.io/challenges/news-homepage-H6SWTa1MFl',
				type: 'pages',
				start_at: '2023-03-16T08:35:00.000Z',
				done_at: '2023-03-16T09:48:00.000Z',
				status: true,
			},
			{
				thumb: 'https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/qh97gysgjrzqyqlig2al.jpg',
				title: 'Qr Code Component',
				slug: 'qr-code',
				url: '/qr-code',
				description:
					"A perfect first challenge if you're new to HTML and CSS. The card layout doesn't shift, so it's ideal if you haven't learned about building responsive layouts yet.",
				href: 'https://www.frontendmentor.io/challenges/qr-code-component-iux_sIO_H',
				type: 'components',
				start_at: '2023-03-06T01:05:00.000Z',
				done_at: '2023-03-06T01:35:00.000Z',
				status: true,
			},
		],
	};
}) satisfies LayoutLoad;
